# Google Cloud Build configuration for Laravel 12 Social Media Application
# This file enables automated builds and deployments via Cloud Build

steps:
  # Step 1: Install Node.js dependencies and build assets
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci --no-audit --no-fund
        npm run build
    id: 'build-assets'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/social-app:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/social-app:latest', '.']
    id: 'build-image'
    waitFor: ['build-assets']

  # Step 3: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/social-app:$BUILD_ID']
    id: 'push-image-with-tag'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/social-app:latest']
    id: 'push-latest-image'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'social-app'
      - '--image=gcr.io/$PROJECT_ID/social-app:$BUILD_ID'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=social-app-service-account@$PROJECT_ID.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:$_SQL_INSTANCE_NAME'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--concurrency=80'
      - '--timeout=300'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--port=80'
      - '--set-env-vars=APP_ENV=production,LOG_CHANNEL=stderr,LOG_LEVEL=info'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image-with-tag', 'push-latest-image']

  # Step 5: Run database migrations (optional - create as separate job)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a one-off job for running migrations
        gcloud run jobs create migrate-job \
          --image=gcr.io/$PROJECT_ID/social-app:$BUILD_ID \
          --region=$_REGION \
          --service-account=social-app-service-account@$PROJECT_ID.iam.gserviceaccount.com \
          --add-cloudsql-instances=$PROJECT_ID:$_REGION:$_SQL_INSTANCE_NAME \
          --memory=1Gi \
          --cpu=1 \
          --max-retries=3 \
          --parallelism=1 \
          --task-count=1 \
          --task-timeout=1800 \
          --set-env-vars=APP_ENV=production \
          --command="php" \
          --args="artisan,migrate,--force" \
          --replace || true
        
        # Execute the migration job
        gcloud run jobs execute migrate-job --region=$_REGION --wait
    id: 'run-migrations'
    waitFor: ['deploy-to-cloud-run']

# Substitution variables
substitutions:
  _REGION: 'us-east1'
  _SQL_INSTANCE_NAME: 'dr3w-social'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '1800s'

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/social-app:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/social-app:latest'